version: '3'

services:
  redis-master:
    image: redis
    container_name: redis-master
    ports:
      - "6379:6379"
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - ./redisdata:/data
  
  product-worker:
    build: .
    #image: satapps/odc-product:0.0.1
    environment:
      - EXTRA_PIP_PACKAGES=${EXTRA_PIP_PACKAGES}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ./data:/tmp/data
    restart: "no"
